"""Add clipboard_history table

Revision ID: 74731e88cc68
Revises: 39bab7927de9
Create Date: 2026-08-23 19:35:10.397109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74731e88cc68'
down_revision: Union[str, None] = '39bab7927de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clipboard_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('source_device_id', sa.Uuid(), nullable=True),
    sa.Column('delivered_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clipboard_history_content_hash', 'clipboard_history', ['content_hash'], unique=False)
    op.create_index('ix_clipboard_history_created_at', 'clipboard_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_clipboard_history_device_id'), 'clipboard_history', ['device_id'], unique=False)
    op.create_index('ix_clipboard_history_device_message', 'clipboard_history', ['device_id', 'message_id'], unique=True)
    op.create_index(op.f('ix_clipboard_history_message_id'), 'clipboard_history', ['message_id'], unique=False)
    op.create_index(op.f('ix_clipboard_history_source_device_id'), 'clipboard_history', ['source_device_id'], unique=False)
    op.alter_column('devices', 'device_type',
               existing_type=postgresql.ENUM('mobile', 'desktop', name='device_type_enum'),
               type_=sa.Enum('mobile', 'desktop', name='devicetype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'device_type',
               existing_type=sa.Enum('mobile', 'desktop', name='devicetype', native_enum=False),
               type_=postgresql.ENUM('mobile', 'desktop', name='device_type_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_clipboard_history_source_device_id'), table_name='clipboard_history')
    op.drop_index(op.f('ix_clipboard_history_message_id'), table_name='clipboard_history')
    op.drop_index('ix_clipboard_history_device_message', table_name='clipboard_history')
    op.drop_index(op.f('ix_clipboard_history_device_id'), table_name='clipboard_history')
    op.drop_index('ix_clipboard_history_created_at', table_name='clipboard_history')
    op.drop_index('ix_clipboard_history_content_hash', table_name='clipboard_history')
    op.drop_table('clipboard_history')
    # ### end Alembic commands ###