"""Add auth_tokens table for device authentication

Revision ID: cf7de40474df
Revises: 001
Create Date: 2026-08-22 12:51:07.818754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf7de40474df'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_tokens_device_active', 'auth_tokens', ['device_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index(op.f('ix_auth_tokens_device_id'), 'auth_tokens', ['device_id'], unique=False)
    op.create_index('ix_auth_tokens_token_hash', 'auth_tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_tokens_token_hash', table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_device_id'), table_name='auth_tokens')
    op.drop_index('ix_auth_tokens_device_active', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###